GET http://localhost:3000/api/transactions

###
POST http://localhost:3000/api/transactions
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZW1haWwuY29tIiwiaWQiOiI2NzkwYzlkZGZjMGE4ZWJlYjJkNGRmNzIiLCJpYXQiOjE3Mzc1NDMwOTB9.tKtSKMtmgbcPDhQrWfYjhiJXqVUtQzX8MYf38CaEcLU

{
    "recipient": "Pharmacy",
    "category": "Other",
    "date": "2024-08-12",
    "amount": 25
}

###
PUT http://localhost:3000/api/transactions/6790d6c694c3c0c77a234625
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZW1haWwuY29tIiwiaWQiOiI2NzkwYzlkZGZjMGE4ZWJlYjJkNGRmNzIiLCJpYXQiOjE3Mzc1NDMwOTB9.tKtSKMtmgbcPDhQrWfYjhiJXqVUtQzX8MYf38CaEcLU

{
    "name": "Pharmacy",
    "category": "Other",
    "date": "2024-08-12",
    "amount": 15
}

###
DELETE http://localhost:3000/api/transactions/6790d588940ee07e73f4b2d2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZW1haWwuY29tIiwiaWQiOiI2NzkwYzlkZGZjMGE4ZWJlYjJkNGRmNzIiLCJpYXQiOjE3Mzc1NDMwOTB9.tKtSKMtmgbcPDhQrWfYjhiJXqVUtQzX8MYf38CaEcLU