GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
content-type: application/json

{
    "email": "test@email.com",
    "name": "Smith",
    "password": "test1234!"
}

###
PATCH http://localhost:3000/api/users
content-type: application/json

{
    "email": "smith@email.com",
    "balance": 1500
}